### ISSUE TITLE
「利用 RBAC + SA 進行 Kubectl 權限控管」範例指令需修正

### ISSUE THREAD

**Issue by acinwinstack** [kairen/kr-static-blog#2]
在文章「[`kr-static-blog/source/_posts/kubernetes/rbac-sa-kubectl.md`](https://github.com/kairen/kr-static-blog/blob/master/source/_posts/kubernetes/rbac-sa-kubectl.md)」的範例中

1. 建立 `dev.conf` 設定檔時，${SERVER} 應對應上方定義的 ${API_SERVER}

2. `dev-user-role.yml` 沒有被` kubectl create`
應在本段落增加 `kubectl create -f dev-user-role.yml`
> 新增 RBAC role 來限制 dev-user 存取權限:
> $ cat <<EOF > dev-user-role.yml
> ...

**Comment by kairen** [comment]
@acinwinstack 謝囉!我修正了!
